-- AlterTable
ALTER TABLE "AssetRegister" ALTER COLUMN "Filter Installed on" SET DATA TYPE TEXT,
ALTER COLUMN "Filter Expiry Date" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "LAPADB" ALTER COLUMN "Risk Assessment WO Date" SET DATA TYPE TEXT,
ALTER COLUMN "Sample On" SET DATA TYPE TEXT,
ALTER COLUMN "Next Sample Date" SET DATA TYPE TEXT,
ALTER COLUMN "Notified On" SET DATA TYPE TEXT,
ALTER COLUMN "Remedial Completed On" SET DATA TYPE TEXT,
ALTER COLUMN "RA Completed On" SET DATA TYPE TEXT,
ALTER COLUMN "Remedial Done On" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "RiskAssessment" ALTER COLUMN "Risk Assessment WO Date" SET DATA TYPE TEXT,
ALTER COLUMN "Sample On" SET DATA TYPE TEXT,
ALTER COLUMN "Next Sample Date" SET DATA TYPE TEXT,
ALTER COLUMN "Notified On" SET DATA TYPE TEXT,
ALTER COLUMN "Remedial Completed On" SET DATA TYPE TEXT,
ALTER COLUMN "RA Completed On" SET DATA TYPE TEXT,
ALTER COLUMN "Remedial Done On" SET DATA TYPE TEXT;
